modLoader = "javafml"
loaderVersion = "47.2.20"
issueTrackerURL = "https://github.com/Bawnorton/Neruina/issues"
license = "MIT"

[[mods]]
modId = "neruina"
version = "2.0.0-beta.9"
displayName = "Neruina"
authors = "Bawnorton"
description = '''
This is a mod that prevents ticking entity and ticking block entity / tile entity crashes from bricking worlds.
'''
logoFile = "icon.png"

[[dependencies.neruina]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20,1.20.4)"
ordering = "NONE"
side = "BOTH"