modLoader = "javafml"
loaderVersion = "${loader_version}"
issueTrackerURL = "https://github.com/Bawnorton/Neruina/issues"
license = "MIT"

[[mods]]
modId = "neruina"
version = "${version}"
displayName = "Neruina"
authors = "Bawnorton"
description = '''
${description}
'''
logoFile = "icon.png"

[[mixins]]
config = "neruina.mixins.json"

[[dependencies.neruina]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_dependency}"
ordering = "NONE"
side = "BOTH"