modLoader = "javafml"
loaderVersion = "0.15.11"
issueTrackerURL = "https://github.com/Bawnorton/Neruina/issues"
license = "MIT"

[[mods]]
modId = "neruina"
version = "2.0.0-beta.9"
displayName = "Neruina"
authors = "Bawnorton"
description = '''
This is a mod that prevents ticking entity and ticking block entity / tile entity crashes from bricking worlds.
'''
logoFile = "icon.png"

[[mixins]]
config = "neruina.mixins.json"

[[dependencies.neruina]]
modId = "minecraft"
type = "required"
versionRange = ">=1.19.3 <1.20"
ordering = "NONE"
side = "BOTH"